### ISSUE TITLE
Qol bugs

### ISSUE THREAD

**Issue by lasersPew** [JVT038/MetaTube#73]
1. Even when I edited the metadata manually, it still asks me to pick one from the list that it searched from musicbrainz, etc even though there's literally no results.
2. It's slow. is there no concurrency in this project?
3. When I recreate the Docker container or just restart it, I get this error:
``` 
ERROR [flask_migrate] Error: Can't locate revision identified by '8046105cb767'
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
```

I can resolve it by moving the app.db out of the folder and letting it recreate the database file then moving it back but now, I can't do it.

**Comment by lasersPew** [comment]
About #2, You can practically make a api call to sponsorblock while it scrapes the data from youtube and after it get the youtube data, call musicbrainz, spotify, and deezer api.

On #1, you can also just add a place where users can add link to either musicbrainz, spotify, or deezer and scrape and use the data.

Tbh, I am irritated that I have to troubleshoot and fix this everyday for days

**Comment by lasersPew** [comment]
To add to this, maybe not use bootstrap as it doesn't look good, even at mobile. maybe the responsive material design would do the trick? Also, An API for media players and other clientsto use as this may be used alongside selfhosted media players.

**Comment by JVT038** [comment]
So after almost a year, I've started with implementing concurrency :D.
Pull the latest image and hopefully it works faster now.

**Comment by lasersPew** [comment]
> So after almost a year, I've started with implementing concurrency :D. Pull the latest image and hopefully it works faster now.

Sorry for the late reply, going back to this project after some while, it is somehow faster though kinda buggy. Welp, imma close this issue.
